### ISSUE TITLE
User_data not working on route steps

### ISSUE THREAD

**Issue by jh7171** [americanexpress/unify-flowret#10]
Setting user_data on route steps doesn't work. ProcessContext::getUserData returns null.

I suspect the problem is in Router.java in the constructor where useData is a parameter but then not used:

```
protected Route(String name, String componentName, String userData, Map<String, Branch> branches, UnitType type) {
    super(name, type);
    this.branches = branches;
    this.componentName = componentName;
  }
```

**Comment by deepakarora3** [comment]
Hi - I have fixed the issue - - please use version 1.2.1. it was exactly what you were saying. Somehow I have always used the user data in a step and so this got missed out. Thanks again for pointing this out. At least it tells me that someone is using Flowret and I am so glad for that. Let me know if all is OK. Closing the issue for now.
