### ISSUE TITLE
error handling in router steps

### ISSUE THREAD

**Issue by jh7171** [americanexpress/unify-flowret#11]
Can you explain or provide and example how error handling in router steps works? I have a class that implements `InvokableRoute` and can't tell any difference between returning a response with and without the `ErrorTuple`.

Snippet 1:
```
@Override
public RouteResponse executeRoute()  {
    ErrorTuple et = new ErrorTuple();
    et.....
    new RouteResponse(UnitResponseType.OK_PROCEED, outBranch, "", et);
}
```

Snippet 2:
```
@Override
public RouteResponse executeRoute()  {
    new RouteResponse(UnitResponseType.OK_PROCEED, outBranch, "");
}
```

**Comment by deepakarora3** [comment]
Are you setting the workbasket when you ERROR_PEND? If you return ERROR_PEND, Flowret looks for the workbasket to pend the case in. I think if you do not specify a workbasket in the response, it will pend into an empty workbasket. So when you say the process sleeps, it is actually pended in a workbasket. Hope this clarifies. I would also encourage you to read the documentation where I have described all this. Do let me know if something is deficient and I can fill in the gaps.
