### ISSUE TITLE
Current implementation doesn't seem support to resume on specific pended point.

### ISSUE THREAD

**Issue by dunglt-iks** [americanexpress/unify-flowret#12]
Hello Deepakarora3,

Assumption that we have flow 
A -> B (p_route)
B -> Branch1 (pause)
B -> Branch2 (pause)
Branch1-> C (join)
Branch2 -> C (join)
C -> End.

When flow is executed. It will be stopped and wait for resume.
Currently flow will be pended at branch1 or branch2 (it depends on which thread completes execution first).
We assume that flow is pended at branch1. But, we would like to resume from branch2.
**How does current implementation support above scenario?** 
In reality, Branch1 represents for Manager1 approval. Branch2 represents for Manager2 approval in parallel, no matter which approval finishes first. Then flow will go to next step if and only if both approvals are done.

**Comment by deepakarora3** [comment]
Yes this feature is not present as of now but can be added in the future. Will take some time to think it through. Thanks.
