### ISSUE TITLE
Unit Test Failed

### ISSUE THREAD

**Issue by krizslash** [americanexpress/unify-flowret#13]
Hi, 

The readme make me interested with this project because it explain clearly about how the library works, compared to other github workflow projects.
I have cloned and tried to run the unit test but some of it failed as shown below:

![image](https://user-images.githubusercontent.com/24690007/185790721-e86b4f05-426d-474e-b67b-f77c33add945.png)

Do I need to configure something before running the unit test?

Thanks!

**Comment by deepakarora3** [comment]
Hi - sorry for the delay in responding - let me get back to you in the next few hours - most likely it is to do with the new line characters.

**Comment by deepakarora3** [comment]
Hi - have corrected and pushed an updated version. Thanks for this. It was a casual oversight from my side in merging code. Closing the issues. Please let me know if you still see any issues.
