### ISSUE TITLE
In addition to process start/end generate event for step start/end

### ISSUE THREAD

**Issue by sebukoleth** [americanexpress/unify-flowret#2]
Since a process consists of multiple steps that are the active execution units it will be helpful to generate events for start/end of these as well. When a process pends it gives the full path to the active path, so we can identify the step.

**Comment by deepakarora3** [comment]
Regarding the start and end events for each step, they can easily be implemented in the application layer as Flowret calls a method on an object provided by the application only. As regards your second question, when a process pends, the Process Context will have all the information you are looking for. Further, take a look at the process life cycle events as well that inform the application that the process is pending, resuming etc. Hope this helps.

**Comment by sebukoleth** [comment]
@deepakarora3 you are right, we can do that, but today there is no event type in Flowret that we can use to indicate that this is a step start/end event.

**Comment by sebukoleth** [comment]
BTW I love the simplicity and extensibility of this framework.

**Comment by deepakarora3** [comment]
Appreciate your kind words! Thanks you!

To your question that there is no event in Flowret that needs to indicate a step start / stop event, there does not need to be. As I said, that flowret relies on the implementation given by the application and so the application knows that it is being invoked for a step or a route. And if it knows that, you can include a layer of abstraction over your step / route implementation. In other words, have a class that flowret calls, this class then calls the step or the route implementation in the application and so this class knows when a step / route is starting and ending.
